
export const ACTIONS = {
    ADD_TASK: 'ADD_TASK',
    DELETE_TASK: 'DELETE_TASK',
    EDIT_TASK: 'EDIT_TASK',
    COMPLETE_TASK: 'COMPLETE_TASK',
    DISPLAY_TASK: 'DISPLAY_TASK',
    DISPLAY_RESPONSE_MESSAGE: 'DISPLAY_RESPONSE_MESSAGE',
    CLEAR_ALL_TASK: 'CLEAR_ALL_TASK',
    SHOW_COMPLETE_TASK: 'SHOW_COMPLETE_TASK',
    SHOW_INCOMPLETE_TASK: "SHOW_INCOMPLETE_TASK",
    SHOW_ALL_TASKS: 'SHOW_ALL_TASKS',
    SORT_TASKS: 'SORT_TASKS',
    SET_USER: 'SET_USER',
}